require: rubocop-rails

AllCops:
  Exclude:
    - "bin/**/*"
    - "config/**/*.rb"
    - "db/**/*.rb"
    - "config.ru"
    - "Gemfile"
    - "Rakefile"
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
